### ISSUE TITLE
Implement Group Names

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/NihonMissionMaker#9]
On import use the defines_unitsAndGroups.sqf file to determine group names based on position in the Arrays. 

Write new group names and their markers to the same file.

Note: Mike may be changing the structure of this file b/c he is a big jerk.

**Comment by MikeMatrix** [comment]
Yup, that's me :shipit:

**Comment by lavinrp** [comment]
"Meat" of the framework process according to pabo: 

_splitName = (vehicleVarName _unit) splitString "_";
if ((count _splitName) < 2) exitWith {};
_nameToSearch = format ["%1_%2", (_splitName select 0), (_splitName select 1)];
{
    if (_nameToSearch == (_x select 0)) exitWith {
        _group setVariable ["F3_GroupID", (_x select 1), true];
    };
} forEach _groupNames;

**Comment by lavinrp** [comment]
Group naming was accomplished by using the group name element in the 3 part naming convention.
Each group is assigned the name of its first unit.
